version: '2'
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - aa-memcached
      - aa-db
    depends_on:
      - aa-memcached
      - aa-db
    environment:
      DEBUG_MODE: "true"
      MYSQL_USER: "aladhan"
      MYSQL_PASSWORD: "aladhan"
      MYSQL_DATABASE: "aladhan_locations"
      MYSQL_HOST_1: "aa-db"
      MYSQL_HOST_2: "aa-db"
      MYSQL_HOST_3: "aa-db"
      MEMCACHED_HOST: "aa-memcached"
      MEMCACHED_PORT: 11211
      GOOGLE_API_KEY: "xyz"
      ASKGEO_ACCOUNT_ID: "1234"
      ASKGEO_API_KEY: "xyz"
    ports:
      - "7070:8080"
    volumes:
      - .:/var/www
    privileged: true
    container_name: aa-app


  #######################################
  # MySQL
  #######################################
  aa-db:
    image: islamicnetwork/api.aladhan.com-db:25-Sep-2019-master
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "aladhan"
      MYSQL_PASSWORD: "aladhan"
      MYSQL_DATABASE: "aladhan_locations"
    container_name: aa-db

  #######################################
  # PHPMyAdmin 1
  #######################################
  aa-pma:
    image: phpmyadmin/phpmyadmin:4.8.3
    environment:
      PMA_HOST: aa-db
    ports:
      - "7071:80"
    links:
      - aa-db
    depends_on:
      - aa-db
    container_name: aa-pma

  #######################################
  # Memcached
  #######################################
  aa-memcached:
    image: memcached:1.5
    #ports:
    #  - "11211:11211"
    container_name: aa-memcached

  #######################################
  # Memcached Admin
  #######################################
  aa-memadmin:
    image: islamicnetwork/phpmemadmin:latest
    ports:
      - "7074:8080"
    environment:
      MEMADMIN_USERNAME: aa
      MEMADMIN_PASSWORD: aa
      MEMCACHED_HOST: aa-memcached
      MEMCACHED_PORT: 11211
    container_name: aa--memadmin
