version: '3'
services:
  aladhan_api:
    build:
      context: .
      dockerfile: Dockerfile.unit
    links:
      - aladhan_memcached
    depends_on:
      - aladhan_memcached
    environment:
      DEBUG: "true" # Any value equals true. To turn off debug mode, comment or delete this env var.
      MEMCACHED_HOST: "aladhan_memcached"
      MEMCACHED_PORT: 11211
      X7X_API_KEY: "d3ec4acaa7978ba6329845ee15fd66d9"
    ports:
      - "80:8080"
    volumes:
      - .:/var/www
    privileged: true
    container_name: aladhan_api

  aladhan_memcached:
    image: memcached:1.6
    container_name: aladhan_memcached

